edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
use_small_heuristics = "Max"
reorder_modules = true
reorder_imports = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = true
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0
format_code_in_doc_comments = true
use_field_init_shorthand = true
use_try_shorthand = true
normalize_comments = true
wrap_comments = true
