/-
  Cathedral Arkhe - Layer 1 Formalization
  Target: T1.1 (Mobius.quotient)
  Reference: CATHEDRAL-ARKHE-WHITEPAPER-v1.1, Appendix C, Tier 1

  Statement: M as quotient of [0,L] × [-w/2, w/2] by (0,y) ~ (L,-y)

  Epistemic Status: L1 (Pure Mathematics)

  Provenance: Generated by AI assistant; revised per external technical review.
  Status: CORRECTED — All proof holes closed. Awaiting `lake build` verification.

  Revision Notes (v3):
  - Symmetry: `c.symm` → `c` (twist branches are self-symmetric in the snd component).
  - Transitivity rw directions: all four equality+twist cases flipped to match goal.
  - Twist+twist merge: `Subtype.ext` removed; `Prod.ext_iff.mpr` used directly.
  - `Rect` and `MobiusBand` changed from `def` to `abbrev` (instance resolution).
  - Imports aligned with Mathlib topology hierarchy.
  - Unused `hw : w > 0` dropped (width positivity not required by the construction).
-/

import Mathlib.Data.Real.Basic
import Mathlib.Topology.Instances.Real.Lemmas
import Mathlib.Topology.Constructions.SumProd
import Mathlib.Order.Interval.Set.Basic

namespace CathedralArkhe.T1

-- Parameter: length of the band. Strict positivity required to prevent
-- a point from simultaneously inhabiting both boundaries (0 and L).
variable (L : ℝ) (w : ℝ)

/--
  The underlying set: the closed rectangle [0, L] × [-w/2, w/2].
  Defined as an `abbrev` (not `def`) so that the subtype topology instance
  is found automatically by Lean's instance search.
-/
abbrev Rect : Type :=
  { p : ℝ × ℝ // p.fst ∈ Set.Icc 0 L ∧ p.snd ∈ Set.Icc (-(w / 2)) (w / 2) }

/--
  The equivalence relation defining the Möbius band.

  Three disjuncts:
  1. Equality (reflexive core).
  2. Twist: left boundary (0, y) identified with right boundary (L, -y).
  3. Twist (symmetric): right boundary (L, y) identified with left (0, -y).

  Mathematical note: every equivalence class has size ≤ 2 (interior points
  are singletons; a boundary point pairs with exactly one point on the
  opposite edge). The condition `L > 0` guarantees that a point cannot sit
  on both boundaries simultaneously, which is what makes the relation
  transitive.
-/
def MobiusRel (p q : Rect L w) : Prop :=
  p.val = q.val ∨
  (p.val.fst = 0 ∧ q.val.fst = L ∧ p.val.snd = -q.val.snd) ∨
  (q.val.fst = 0 ∧ p.val.fst = L ∧ q.val.snd = -p.val.snd)

/--
  The Setoid instance required by Lean's `Quotient`.

  Reflexivity and symmetry are immediate. Transitivity is the core of T1.1:
  composing two boundary identifications either yields identity, a single
  twist, or a contradiction (when `L > 0` rules out a point on both edges).
-/
def mobiusSetoid (hL : L > 0) : Setoid (Rect L w) where
  r := MobiusRel L w
  iseqv := by
    refine ⟨?refl, ?symm, ?trans⟩
    · -- Reflexivity
      intro x
      exact Or.inl rfl
    · -- Symmetry
      rintro x y (h_eq | ⟨a, b, c⟩ | ⟨a, b, c⟩)
      · exact Or.inl h_eq.symm
      · exact Or.inr (Or.inr ⟨a, b, c⟩)   -- c already has the right shape
      · exact Or.inr (Or.inl ⟨a, b, c⟩)   -- c already has the right shape
    · -- Transitivity (3 × 3 = 9 cases)
      rintro x y z hxy hyz
      rcases hxy with hxy | hxy | hxy
      · -- x = y
        rcases hyz with hyz | hyz | hyz
        · -- y = z  ⇒  x = z
          exact Or.inl (hxy.trans hyz)
        · -- y twist→ z  ⇒  x twist→ z
          exact Or.inr (Or.inl (by rw [hxy]; exact hyz))
        · -- y twist← z  ⇒  x twist← z
          exact Or.inr (Or.inr (by rw [hxy]; exact hyz))
      · -- x twist→ y  :  x.1 = 0, y.1 = L, x.2 = -y.2
        rcases hyz with hyz | hyz | hyz
        · -- y = z  ⇒  x twist→ z
          exact Or.inr (Or.inl (by rw [← hyz]; exact hxy))
        · -- y twist→ z  :  y.1 = 0, z.1 = L, y.2 = -z.2
          -- But y.1 = L (from hxy) and y.1 = 0 (from hyz) ⇒ contradiction.
          exfalso
          have h1 : y.val.fst = L := hxy.2.1
          have h2 : y.val.fst = 0 := hyz.1
          linarith
        · -- y twist← z  :  z.1 = 0, y.1 = L, z.2 = -y.2
          -- Consistent: y.1 = L in both. Then x.1 = 0, z.1 = 0, x.2 = -y.2 = z.2.
          refine Or.inl (Prod.ext_iff.mpr ⟨?_, ?_⟩)
          · linarith [hxy.1, hyz.1]
          · linarith [hxy.2.2, hyz.2.2]
      · -- x twist← y  :  y.1 = 0, x.1 = L, y.2 = -x.2
        rcases hyz with hyz | hyz | hyz
        · -- y = z  ⇒  x twist← z
          exact Or.inr (Or.inr (by rw [← hyz]; exact hxy))
        · -- y twist→ z  :  y.1 = 0, z.1 = L, y.2 = -z.2
          -- Consistent: y.1 = 0 in both. Then x.1 = L, z.1 = L, x.2 = -y.2 = z.2.
          refine Or.inl (Prod.ext_iff.mpr ⟨?_, ?_⟩)
          · linarith [hxy.2.1, hyz.2.1]
          · linarith [hxy.2.2, hyz.2.2]
        · -- y twist← z  :  z.1 = 0, y.1 = L, z.2 = -y.2
          -- But y.1 = 0 (from hxy) and y.1 = L (from hyz) ⇒ contradiction.
          exfalso
          have h1 : y.val.fst = 0 := hxy.1
          have h2 : y.val.fst = L := hyz.2.1
          linarith

/--
  T1.1 TARGET: The Möbius band as a quotient space.

  Defined as an `abbrev` so that the quotient topology instance is found
  automatically by instance search (preparatory for T1.2 non-orientability).
-/
abbrev MobiusBand (hL : L > 0) : Type := Quotient (mobiusSetoid L w hL)

/--
  The quotient topology on the Möbius band.
  Inferred automatically from the Euclidean topology on ℝ² via the
  quotient construction.
-/
instance (hL : L > 0) : TopologicalSpace (MobiusBand L w hL) := inferInstance

end CathedralArkhe.T1
